CREATE PROCEDURE %%DYN-UNPACK-FOR-FTS%%(rid IN ROWID, b IN OUT CLOB) AS
BEGIN
 FOR x IN (SELECT %%DEST-BLOB%% t FROM %%DEST-TABLE%% WHERE rowid=rid
   AND %%DEST-BLOB%% IS NOT NULL
   AND DBMS_LOB.GETLENGTH(%%DEST-BLOB%%)>0 
    ) LOOP 
  %%JCR_FTS_UTL_PKG%%.unpack(x.t,b);
 END LOOP;
END;