CREATE PROCEDURE %%LOG-FTS-ERR-PROC%%(
 p_id IN NUMBER,
 p_code IN VARCHAR2,
 p_type IN VARCHAR2,
 p_msg  IN VARCHAR2
) AS
 PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
 INSERT INTO %%ERR-TABLE%%(
  %%ERR-ID-COL%%,  %%ERR-CODE-COL%%,  %%ERR-TYPE-COL%%,%%ERR-MSG-COL%%
 ) VALUES(
  p_id, p_code, p_type, SUBSTR(p_msg,1,%%ERR-MSG-MAX-LEN%%)
 );
 COMMIT;
END;