CREATE PROCEDURE %%USER-SCHEMA%%.PREMOVETREE(
 @nodeid NUMERIC(9),
 @userid NVARCHAR(254),
 @grouplist NVARCHAR(4000)
) AS
DECLARE
 @secid NUMERIC(9),
 @childsecid NUMERIC(9),
 @rc INT
BEGIN
 IF @nodeid IS NULL OR @userid IS NULL RETURN 0
 SELECT @secid=(SELECT SECURITY_ID FROM CM_NODE WHERE ID=@nodeid)
 IF @secid IS NULL RETURN 0
 EXEC @rc=PREMOVE @secid,@userid,@grouplist
 IF @rc=0 RETURN 0
 DECLARE X CURSOR LOCAL FAST_FORWARD FOR SELECT DISTINCT CM_NODE.SECURITY_ID
  FROM CM_NODE JOIN CM_NODE_PARENTS ON CM_NODE_PARENTS.NODE_ID=CM_NODE.ID
  WHERE CM_NODE_PARENTS.PARENT_ID=@nodeid
 OPEN X
 FETCH X INTO @childsecid
 WHILE (@@FETCH_STATUS=0) BEGIN
  IF @childsecid IS NULL BEGIN
   CLOSE X
   DEALLOCATE X
   RETURN 0
  END
  IF @childsecid<>@secid BEGIN
   EXEC @rc=PREMOVE @childsecid,@userid,@grouplist
   IF @rc=0 BEGIN
    CLOSE X
    DEALLOCATE X
    RETURN 0
   END
  END
  FETCH X INTO @childsecid
 END
 CLOSE X
 DEALLOCATE X
 RETURN 1
END