CREATE PROCEDURE %%USER-SCHEMA%%.PREMOVE(
 @secid NUMERIC(9),
 @userid NVARCHAR(254),
 @grouplist NVARCHAR(4000)
) AS
DECLARE
 @uid NVARCHAR(254),
 @gid NVARCHAR(254),
 @perm BIT,
 @rc INT,
 @rows INT
BEGIN
 IF @secid IS NULL OR @userid IS NULL RETURN 0
 DECLARE C CURSOR LOCAL FAST_FORWARD FOR SELECT GROUP_ID,USER_ID,P_REMOVE FROM CM_ACE WHERE SECURITY_ID=@secid
   ORDER BY CASE WHEN USER_ID IS NOT NULL AND USER_ID=@userid THEN 0 ELSE 1 END ASC
 OPEN C
 FETCH C INTO @gid,@uid,@perm
 SET @rows=0
 SET @rc=NULL
 WHILE (@@FETCH_STATUS=0) BEGIN
  SET @rows=@rows+1
  IF @uid=@userid AND @perm IS NOT NULL BEGIN
   CLOSE C
   DEALLOCATE C
   RETURN @perm
  END
  IF CHARINDEX(','+@gid+',',','+@grouplist+',')>0 AND @perm IS NOT NULL BEGIN
   IF @perm=0 BEGIN
    CLOSE C
    DEALLOCATE C
    RETURN 0
   END
   SET @rc=@perm
  END
  FETCH C INTO @gid,@uid,@perm
 END
 CLOSE C
 DEALLOCATE C
 IF @rows=0 BEGIN
  RETURN 1
 END
 IF @rc IS NULL BEGIN
  RETURN 0
 END
 RETURN @rc
END