CREATE PROCEDURE %%USER-SCHEMA%%.%%STOPWORD-COPY-PROC%%
 @DataFilePath varchar(250) AS 
DECLARE @STMT nvarchar(1000)
BEGIN
 IF EXISTS (SELECT * FROM sysobjects WHERE name='%%STOPWORD-TMP%%')
 BEGIN
  DROP TABLE %%USER-SCHEMA%%.%%STOPWORD-TMP%%
 END
 CREATE TABLE %%USER-SCHEMA%%.%%STOPWORD-TMP%%  (%%STOPWORD-COL%% varchar(1000))
 SET @STMT='BULK INSERT %%USER-SCHEMA%%.%%STOPWORD-TMP%% FROM '''+@DataFilePath+''''
 EXEC sp_executesql @STMT
 INSERT INTO %%USER-SCHEMA%%.%%STOPWORD-TAB%% SELECT DISTINCT %%STOPWORD-COL%% FROM %%USER-SCHEMA%%.%%STOPWORD-TMP%%
   WHERE %%STOPWORD-COL%% IS NOT NULL AND
    %%STOPWORD-COL%% NOT IN (SELECT %%STOPWORD-COL%% from %%USER-SCHEMA%%.%%STOPWORD-TAB%%)
 DROP TABLE %%USER-SCHEMA%%.%%STOPWORD-TMP%%
END

