CREATE TRIGGER %%TRIGGER_NAME%% ON %%USER-NAME%%.%%TABLE-UNSTRUCTURED-PROP%% AFTER INSERT,UPDATE AS
IF UPDATE(DOUBLE_VALUE) OR UPDATE(DATE_VALUE)
 OR UPDATE(BOOLEAN_VALUE) OR UPDATE(LONG_VALUE)
UPDATE %%TABLE-UNSTRUCTURED-PROP%% SET STRING_VALUE=(CASE
  WHEN i.DOUBLE_VALUE IS NOT NULL THEN CAST(i.DOUBLE_VALUE AS VARCHAR)
  WHEN i.DATE_VALUE IS NOT NULL THEN CAST(i.DATE_VALUE AS VARCHAR)
  WHEN i.BOOLEAN_VALUE IS NOT NULL THEN CAST(i.BOOLEAN_VALUE AS VARCHAR)
  WHEN i.LONG_VALUE IS NOT NULL THEN CAST(i.LONG_VALUE AS VARCHAR)
  ELSE i.STRING_VALUE END)
FROM inserted i WHERE %%TABLE-UNSTRUCTURED-PROP%%.ID=i.ID
